# Перцептрон Розенблатта

Перцептрон - это модель, предложенная Френком Розенблаттом в 1957 году и являющаяся прообразом современных нейронных сетей. По своей сути она представляет из себя значительно упрощенную схему восприятия информации мозгом. Целью этого практического задания будет реализация собственной модели перцептрона. Давайте разберем схему работы этого алгоритма в деталях.

* Мы работаем с тренировочной выборкой $S = \{(x_i, y_i)| i \in \{1,...,m\} \}$
* Инициализируем веса $\omega^{(0)} \leftarrow 0$ нулевым вектором.
* Инициализирует bias параметр $b = 0$.
* В начальный момент времени номер шага $t=0$.
* Задаем learning rate $\eta > 0$.
* Пока значение $t < t_{\max}$
    * случайно выбираем объект из тренировочной выборки $(x_i, y_i) \in S$.
    * если выполняется условие $y_i (\langle \omega^{(t)}, x_i\rangle + b) \leq 0$ тогда
        * $b^{(t+1)} \leftarrow b^{(t)} + \eta \times y_i$.
        * $\omega^{(t+1)} \leftarrow \omega^{(t)} + \eta \times y_i \times x_i$.
    * далее, обновляем $t \leftarrow t+1$.

Таким образом, финальное значение ветора весов $\omega$ и bias параметра $b$ позволяют классифицировать новый объект $x$. Если $(\langle \omega, x \rangle + b) \geq 0$, то мы относим объект к классу $+1$, в противном случае мы относим объект к классу $-1$.

Для начала загрузим датасет для задачи классификации цветков Ириса с помощь функции `load_iris` из `sklearn.datasets`. Давайте подготовим данные для задачи бинарной классификации. Для этого выберем первые 100 элементов из данного набора данных. Так же преобразуем класс $0$ в класс $-1$.

In [74]:
import numpy as np
from sklearn.datasets import load_iris

X, y = load_iris(return_X_y=True)
X, y = X[:100], y[:100]
num_features = X.shape[1]
y = np.array([1 if y_i == 1 else -1 for y_i in y])

In [75]:
# Массив входных данных
# Каждая строка массива - измерения отдельно взятого цветка ириса
X[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [10]:
# Выходные данные - метки классов

In [98]:
y[:5]

array([-1, -1, -1, -1, -1])

In [99]:
y[-5:]

array([1, 1, 1, 1, 1])

Реализуйте алгоритм перцептрона приведенный выше. Для выборки случайного объекта из тренировочного датасета по индексу используйте функцию `randint` из модуля `random` с параметрами 0 и n, где n - это размер тренировочно выборки. Перед запуском итераций алгоритма установите `random.seed(42)`. Вы можете реализовать перцептрон в качестве класса с интерфейсом, похожим на интерфейсы моделей из `scikit-learn`. Для этого достаточно реализовать методы `fit` и `predict` для решения этого практического задания. Однако, ваша реализация может отличаться. Необходимое требование - это использование генератора случайных чисел, описанного выше.

### *РЕШЕНИЕ*

In [102]:
from sklearn.base import BaseEstimator
import random

class Perceptron(BaseEstimator):
    
    def __init__(self, eta, t_max):
        # Задаем learning rate
        self.eta = eta
        # Задаем максимальное число шагов на обучение
        self.t_max = t_max
    
    def fit(self, X, y=None):
        # Инициализируем веса нулевым вектором.
        self.coef_ = np.zeros(X.shape[1])
        # Инициализирует bias параметр
        self.intercept_ = 0
        # Обучаем модель
        random.seed(42)
        for _ in range(self.t_max):
            # случайно выбираем объект из тренировочной выборки
            i = random.randint(0, X.shape[0] - 1)
            if (y[i]*(np.dot(self.coef_, X[i]) + self.intercept_) <= 0):
                self.intercept_ += self.eta * y[i]
                self.coef_ += self.eta * y[i] * X[i]
    
    def predict(self, X):
        # Инициализируем массив предсказанных меток классов
        prediction = np.array([])
        for x in X:
            if (np.dot(self.coef_, x) + self.intercept_ >= 0):
                prediction = np.append(prediction, 1)
            else:
                prediction = np.append(prediction, -1)
        return prediction
    
    def score(self, X, y):
        return np.sum(self.predict(X) == y) / len(y)


Следующим шагом является проверка нашей модели. Случайно разделите выборку на тренировочный и тестовый датасет, используя функцию `tran_test_split` с параметрами `test_size=0.25` и `random_state=10`. Запустите обучение модели с параметрами $\eta=0.1$ и $t_{\max}=40$. Оцените качество на тестовой выборке и запишите результат в переменную `score` с точность до двух знаков после запятой, используя метрику `accuracy`. Это значение и будет являться ответом на это практическое задание.

### *РЕШЕНИЕ*

In [103]:
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=10, test_size=0.25
)

In [104]:
model = Perceptron(0.1, 40)

In [109]:
model.fit(X_train, y_train)

In [110]:
# Полученные веса
model.coef_

array([-0.2 , -0.89,  1.26,  0.51])

In [111]:
# Полученное смещение
model.intercept_

-0.1

In [112]:
# Предсказания на тестовой выборке
model.predict(X_test)

array([-1., -1., -1., -1.,  1., -1.,  1., -1., -1.,  1., -1., -1.,  1.,
        1.,  1.,  1.,  1., -1.,  1., -1.,  1.,  1.,  1., -1.,  1.])

In [115]:
# Точность на тренировочной выборке
model.score(X_train, y_train)

1.0

In [113]:
# Точность на тестовой выборке
model.score(X_test, y_test)

1.0

# Строка с ответами

In [114]:
print("score {0:.2f}".format(model.score(X_test, y_test)))

score 1.00
